/*******************************************************************************************
   File           :  Oufff_LibErrorCode.h
   Authors        :  Fifi_one       (philippe.bechet@cpe.fr)
   Team           :  OUFFF TEAM

   Description    :  Give all Error generated by Oufff_Lib project
   History        :
      2008_05_02 (Fifi_one)   : Initial Version

   Dependencies   :
      None
/*******************************************************************************************/

#ifndef OUFFF_LIBERRORCODE_H
#define OUFFF_LIBERRORCODE_H


// Global Error ---------------------------------------------------------------------------
#define OUFFF_LIB_NOERR										0x00000000						// No Errors

#define OUFFF_LIB_INVALID_PARAM							0x00000001						// Param given is not valid

// RS232 Error ----------------------------------------------------------------------------
#define OUFFF_LIB_RS232_INVALID_PARAM					OUFFF_LIB_INVALID_PARAM		// Param given is not valid
#define OUFFF_LIB_RS232_UNABLE_OPEN_PORT				0x00100002						// Unable to open port
#define OUFFF_LIB_RS232_UNABLE_SET_CONFIG				0x00100003						// Unable to set param to config port
#define OUFFF_LIB_RS232_UNABLE_READ_CONFIG			0x00100004						// Unable to read param to config port
#define OUFFF_LIB_RS232_UNABLE_CLOSE_PORT				0x00100005						// Unable to close port
#define OUFFF_LIB_RS232_ERR_SEND							0x00100006						// Error during sending data
#define OUFFF_LIB_RS232_ERR_RCV							0x00100007						// Error during reciving data


// Config File Error ----------------------------------------------------------------------
#define OUFFF_LIB_CONFIGFILE_INVALID_PARAM			OUFFF_LIB_INVALID_PARAM		// Param given is not valid
#define OUFFF_LIB_CONFIGFILE_UNABLE_OPEN_FILE		0x00200002						// Unable to open given file
#define OUFFF_LIB_CONFIGFILE_UNABLE_CLOSE_FILE		0x00200003						// Unable to close config file
#define OUFFF_LIB_CONFIGFILE_FILE_NOT_OPENED			0x00200004						// Config file is not opened
#define OUFFF_LIB_CONFIGFILE_PARAM_NOT_FOUND			0x00200005						// Param wanted is not found in file


#endif // OUFFF_LIBERRORCODE_H